steps:
  - name: node:12.0.0
    entrypoint: yarn
    args: ["install"]
  - name: node:12.0.0
    entrypoint: yarn
    args: ["web:build"]
    id: "web-build"
  - name: node:12.0.0
    entrypoint: yarn
    args: ["server:build"]
    id: "server-build"
    waitFor: ["web-build"]
  - name: node
    entrypoint: npm
    args:
      [
        "rebuild",
        "--target=15.0.0",
        "--target_platform=linux",
        "--target_arch=x64",
        "--target_libc=glibc",
        "--update-binary",
      ]
    dir: "packages/cloud"
  - name: gcr.io/sellia-42377/firebase
    args: ["deploy", "--project=sellia-42377"]
    dir: "packages/cloud"
# steps:
#
#   - name: "gcr.io/cloud-builders/yarn"
#     args: ["install"]
#   # Build
#   - name: "gcr.io/cloud-builders/yarn"
#     args: ["run", "web:build"]
#   - name: "gcr.io/cloud-builders/yarn"
#     args: ["run", "server:build"]
#   # Deploy
#   - name: "gcr.io/cloud-builders/yarn"
#     args: ["run", "deploy"]

# - name: node:15.0.0
#     entrypoint: npm
#     args:
#       [
#         "rebuild",
#         "--target=15.0.0",
#         "--target_platform=linux",
#         "--target_arch=x64",
#         "--target_libc=glibc",
#         "--update-binary",
#       ]
