# steps:
#   - name: node
#     entrypoint: yarn
#     args: ["web:build"]
#   - name: node
#     entrypoint: yarn
#     args: ["server:build"]
#   - name: node
#     entrypoint: yarn
#     args: ["deploy"]

steps:
  # Install
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]
  # Build
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "web:build"]
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "server:build"]
  # Deploy
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "deploy"]
